         SUBROUTINE ZERO(A,LEN)
C
C     ZEROS OUT THE FIRST LEN ELEMENTS OF DOUBLE PRECISION VECTOR A.
C
C     END
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      DIMENSION A(LEN)
      DO 10 I=1,LEN
         A(I)=0.D0
 10   CONTINUE
      RETURN
      END
      
