
      SUBROUTINE GENNBO_MAIN
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)

      CALL GETREC(-1,'JOBARC','NREALATM',1,NATOMS)
      CALL GETREC(-1,'JOBARC','NAOBASFN',1,NBAS)
      CALL GENNBO_GENFILE(NATOMS,NBAS)

      RETURN
      END

