      SUBROUTINE SEEKLB(TARGET, IERR, IMODE, IUNIT)
C
C THIS ROUTINE FINDS A RECORD LABEL IN A VPROPS OUTPUT FILE.
C
      CHARACTER*8 DUM1, DUM2, DUM3, TITLE, TARGET
      IF(IMODE .EQ. 0) THEN
         REWIND (IUNIT)
      ENDIF
      IERR = 0
 10   READ (UNIT=IUNIT, END=100, ERR=101) DUM1, DUM2, DUM3, TITLE
      IF (TITLE .EQ. TARGET) THEN
         RETURN
      ELSE
         GOTO 10
      ENDIF
C
 100  IERR=1
C
      RETURN

 101  WRITE(6,2000)
      CALL ERREX
C
 2000 FORMAT(T3,'@SEEKLB-F, I/O error on file VPOUT.')
C
      END
