      INTEGER FUNCTION IFINDNE(N,A,ISKIP,TARGET,TOLER)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      DIMENSION A(ISKIP,*)
      I = 1
      DO WHILE (ABS(A(1,I)-TARGET).LT.TOLER.AND.I.LT.N+1)
         I = I + 1
      END DO
      IFINDNE = I
      RETURN
      END
