
C ROUTINE TO CONSTRUCT POINTER LIST FOR FINITE DIFFERENCE CALCULATIONS.
C  IPTR(I)=J MEANS THAT THE SYMMETRY OPERATION MAPS ATOM I INTO ATOM J.

      SUBROUTINE STPTR(N,NORD1,NORD2,IPTR)
      IMPLICIT INTEGER (A-Z)
      DIMENSION NORD1(N),NORD2(N),IPTR(N)
      DO I=1,N
         J=NORD1(I)
         K=NORD2(I)
         IPTR(J)=K
      END DO
      RETURN
      END

