#ifndef _IACHAR_H_
#define _IACHAR_H_

#define _IACHAR_NULL_CHARACTER         0
#define _IACHAR_NULL                   0
#define _IACHAR_NUL                    0
#define _IACHAR_START_OF_HEADER        1
#define _IACHAR_SOH                    1
#define _IACHAR_START_OF_TEXT          2
#define _IACHAR_STX                    2
#define _IACHAR_END_OF_TEXT            3
#define _IACHAR_ETX                    3
#define _IACHAR_END_OF_TRANSMISSION    4
#define _IACHAR_EOT                    4
#define _IACHAR_ENQUIRY                5
#define _IACHAR_ENQ                    5
#define _IACHAR_ACKNOWLEDGE            6
#define _IACHAR_ACK                    6
#define _IACHAR_RING                   7
#define _IACHAR_BELL                   7
#define _IACHAR_BEL                    7
#define _IACHAR_BACKSPACE              8
#define _IACHAR_BS                     8
#define _IACHAR_HORIZONTAL_TAB         9
#define _IACHAR_TAB                    9
#define _IACHAR_HT                     9
#define _IACHAR_LINE_FEED              10
#define _IACHAR_LF                     10
#define _IACHAR_VERTICAL_TAB           11
#define _IACHAR_VT                     11
#define _IACHAR_FORM_FEED              12
#define _IACHAR_FF                     12
#define _IACHAR_CARRIAGE_RETURN        13
#define _IACHAR_CR                     13
#define _IACHAR_SHIFT_OUT              14
#define _IACHAR_SO                     14
#define _IACHAR_SHIFT_IN               15
#define _IACHAR_SI                     15
#define _IACHAR_DATA_LINK_ESCAPE       16
#define _IACHAR_DLE                    16
#define _IACHAR_DEVICE_CONTROL_1       17
#define _IACHAR_DC1                    17
#define _IACHAR_DEVICE_CONTROL_2       18
#define _IACHAR_DC2                    18
#define _IACHAR_DEVICE_CONTROL_3       19
#define _IACHAR_DC3                    19
#define _IACHAR_DEVICE_CONTROL_4       20
#define _IACHAR_DC4                    20
#define _IACHAR_NEGATIVE_ACKNOWLEDGE   21
#define _IACHAR_NAK                    21
#define _IACHAR_SYNCHRONIZE            22
#define _IACHAR_SYN                    22
#define _IACHAR_END_TRANSMISSION_BLOCK 23
#define _IACHAR_TB                     23
#define _IACHAR_CANCEL                 24
#define _IACHAR_CAN                    24
#define _IACHAR_END_OF_MEDIUM          25
#define _IACHAR_EM                     25
#define _IACHAR_SUBSTITUTE             26
#define _IACHAR_SUB                    26
#define _IACHAR_ESCAPE                 27
#define _IACHAR_ESC                    27
#define _IACHAR_FILE_SEPARATOR         28
#define _IACHAR_FS                     28
#define _IACHAR_GROUP_SEPARATOR        29
#define _IACHAR_GS                     29
#define _IACHAR_RECORD_SEPARATOR       30
#define _IACHAR_RS                     30
#define _IACHAR_UNIT_SEPARATOR         31
#define _IACHAR_US                     31
#define _IACHAR_SPACE                  32
#define _IACHAR_SP                     32
#define _IACHAR_EXCLAMATION            33
#define _IACHAR_EXCL                   33
#define _IACHAR_BANG                   33
#define _IACHAR_QUOTATION              34
#define _IACHAR_DOUBLE_QUOTES          34
#define _IACHAR_QUOTES                 34
#define _IACHAR_DOUBLE_QUOTE           34
#define _IACHAR_QUOTE                  34
#define _IACHAR_QUOT                   34
#define _IACHAR_NUMBER                 35
#define _IACHAR_NUM                    35
#define _IACHAR_POUND                  35
#define _IACHAR_HASH                   35
#define _IACHAR_DOLLAR                 36
#define _IACHAR_PERCENT                37
#define _IACHAR_PERCNT                 37
#define _IACHAR_AMPERSAND              38
#define _IACHAR_AMP                    38
#define _IACHAR_AND                    38
#define _IACHAR_APOSTROPHE             39
#define _IACHAR_APOS                   39
#define _IACHAR_SINGLE_QUOTES          39
#define _IACHAR_SINGLE_QUOTE           39
#define _IACHAR_OPEN_PARENTHESIS       40
#define _IACHAR_O_PARENTHESIS          40
#define _IACHAR_LEFT_PARENTHESIS       40
#define _IACHAR_L_PARENTHESIS          40
#define _IACHAR_LPAR                   40
#define _IACHAR_CLOSE_PARENTHESIS      41
#define _IACHAR_C_PARENTHESIS          41
#define _IACHAR_RIGHT_PARENTHESIS      41
#define _IACHAR_R_PARENTHESIS          41
#define _IACHAR_RPAR                   41
#define _IACHAR_ASTERISK               42
#define _IACHAR_ASTERIX                42 /* Should this be allowed? */
#define _IACHAR_AST                    42
#define _IACHAR_STAR                   42
#define _IACHAR_PLUS                   43
#define _IACHAR_COMMA                  44
#define _IACHAR_HYPHEN                 45
#define _IACHAR_MINUS                  45
#define _IACHAR_PERIOD                 46
#define _IACHAR_DECIMAL                46
#define _IACHAR_DOT                    46
#define _IACHAR_FORWARD_SLASH          47
#define _IACHAR_FORWARDSLASH           47
#define _IACHAR_SLASH                  47
#define _IACHAR_VIRGULE                47
#define _IACHAR_SOLIDUS                47
#define _IACHAR_SOL                    47
#define _IACHAR_0                      48
#define _IACHAR_ZERO                   48
#define _IACHAR_1                      49
#define _IACHAR_ONE                    49
#define _IACHAR_2                      50
#define _IACHAR_TWO                    50
#define _IACHAR_3                      51
#define _IACHAR_THREE                  51
#define _IACHAR_4                      52
#define _IACHAR_FOUR                   52
#define _IACHAR_5                      53
#define _IACHAR_FIVE                   53
#define _IACHAR_6                      54
#define _IACHAR_SIX                    54
#define _IACHAR_7                      55
#define _IACHAR_SEVEN                  55
#define _IACHAR_8                      56
#define _IACHAR_EIGHT                  56
#define _IACHAR_9                      57
#define _IACHAR_NINE                   57
#define _IACHAR_COLON                  58
#define _IACHAR_SEMICOLON              59
#define _IACHAR_SEMI                   59
#define _IACHAR_LESS_THAN              60
#define _IACHAR_LESSTHAN               60
#define _IACHAR_LESS                   60
#define _IACHAR_LT                     60
#define _IACHAR_EQUALS                 61
#define _IACHAR_EQUAL                  61
#define _IACHAR_EQ                     61
#define _IACHAR_GREATER_THAN           62
#define _IACHAR_GREATERTHAN            62
#define _IACHAR_GREATER                62
#define _IACHAR_GT                     62
#define _IACHAR_QUESTION               63
#define _IACHAR_QUEST                  63
#define _IACHAR_COMMERCIAL_AT          64
#define _IACHAR_COMMAT                 64
#define _IACHAR_AT                     64
#define _IACHAR_A                      65
#define _IACHAR_B                      66
#define _IACHAR_C                      67
#define _IACHAR_D                      68
#define _IACHAR_E                      69
#define _IACHAR_F                      70
#define _IACHAR_G                      71
#define _IACHAR_H                      72
#define _IACHAR_I                      73
#define _IACHAR_J                      74
#define _IACHAR_K                      75
#define _IACHAR_L                      76
#define _IACHAR_M                      77
#define _IACHAR_N                      78
#define _IACHAR_O                      79
#define _IACHAR_P                      80
#define _IACHAR_Q                      81
#define _IACHAR_R                      82
#define _IACHAR_S                      83
#define _IACHAR_T                      84
#define _IACHAR_U                      85
#define _IACHAR_V                      86
#define _IACHAR_W                      87
#define _IACHAR_X                      88
#define _IACHAR_Y                      89
#define _IACHAR_Z                      90
#define _IACHAR_OPEN_SQUARE_BRACKET    91
#define _IACHAR_O_SQUARE_BRACKET       91
#define _IACHAR_LEFT_SQUARE_BRACKET    91
#define _IACHAR_L_SQUARE_BRACKET       91
#define _IACHAR_LSQB                   91
#define _IACHAR_OPEN_BRACKET           91
#define _IACHAR_O_BRACKET              91
#define _IACHAR_LEFT_BRACKET           91
#define _IACHAR_L_BRACKET              91
#define _IACHAR_BACK_SLASH             92
#define _IACHAR_BACKSLASH              92
#define _IACHAR_REVERSE_SOLIDUS        92
#define _IACHAR_BSOL                   92
#define _IACHAR_CLOSE_SQUARE_BRACKET   93
#define _IACHAR_C_SQUARE_BRACKET       93
#define _IACHAR_RIGHT_SQUARE_BRACKET   93
#define _IACHAR_R_SQUARE_BRACKET       93
#define _IACHAR_RSQB                   93
#define _IACHAR_CLOSE_BRACKET          93
#define _IACHAR_C_BRACKET              93
#define _IACHAR_RIGHT_BRACKET          93
#define _IACHAR_R_BRACKET              93
#define _IACHAR_CIRCUMFLEX             94
#define _IACHAR_CIRC                   94
#define _IACHAR_CARET                  94
#define _IACHAR_HAT                    94
#define _IACHAR_UNDERSCORE             95
#define _IACHAR_LOWBAR                 95
#define _IACHAR_HORIZONTAL_BAR         95
#define _IACHAR_HORBAR                 95
#define _IACHAR__                      95
#define _IACHAR_ACCENT                 96
#define _IACHAR_GRAVE                  96
#define _IACHAR_a                      97
#define _IACHAR_b                      98
#define _IACHAR_c                      99
#define _IACHAR_d                      100
#define _IACHAR_e                      101
#define _IACHAR_f                      102
#define _IACHAR_g                      103
#define _IACHAR_h                      104
#define _IACHAR_i                      105
#define _IACHAR_j                      106
#define _IACHAR_k                      107
#define _IACHAR_l                      108
#define _IACHAR_m                      109
#define _IACHAR_n                      110
#define _IACHAR_o                      111
#define _IACHAR_p                      112
#define _IACHAR_q                      113
#define _IACHAR_r                      114
#define _IACHAR_s                      115
#define _IACHAR_t                      116
#define _IACHAR_u                      117
#define _IACHAR_v                      118
#define _IACHAR_w                      119
#define _IACHAR_x                      120
#define _IACHAR_y                      121
#define _IACHAR_z                      122
#define _IACHAR_OPEN_CURLY_BRACE       123
#define _IACHAR_O_CURLY_BRACE          123
#define _IACHAR_LEFT_CURLY_BRACE       123
#define _IACHAR_L_CURLY_BRACE          123
#define _IACHAR_LCUB                   123
#define _IACHAR_OPEN_BRACE             123
#define _IACHAR_O_BRACE                123
#define _IACHAR_LEFT_BRACE             123
#define _IACHAR_L_BRACE                123
#define _IACHAR_PIPE                   124
#define _IACHAR_VERTICAL_BAR           124
#define _IACHAR_VERBAR                 124
#define _IACHAR_BAR                    124
#define _IACHAR_CLOSE_CURLY_BRACE      125
#define _IACHAR_C_CURLY_BRACE          125
#define _IACHAR_RIGHT_CURLY_BRACE      125
#define _IACHAR_R_CURLY_BRACE          125
#define _IACHAR_RCUB                   125
#define _IACHAR_CLOSE_BRACE            125
#define _IACHAR_C_BRACE                125
#define _IACHAR_RIGHT_BRACE            125
#define _IACHAR_R_BRACE                125
#define _IACHAR_TILDE                  126
#define _IACHAR_DELETE                 127
#define _IACHAR_DEL                    127

#endif /* _IACHAR_H_ */
